// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcscO9vECkwxPtLZ9YumQhx1LDbtnc37w',
    appId: '1:825089598653:web:a351439f6dd23b962e83d4',
    messagingSenderId: '825089598653',
    projectId: 'firestore-1b054',
    authDomain: 'firestore-1b054.firebaseapp.com',
    storageBucket: 'firestore-1b054.appspot.com',
    measurementId: 'G-QGRKPB6PSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUmee3n2mTrgLicAcva_TkC8pMCKk323U',
    appId: '1:825089598653:android:3d12edf7ea12624b2e83d4',
    messagingSenderId: '825089598653',
    projectId: 'firestore-1b054',
    storageBucket: 'firestore-1b054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2HpaUBVqUeCMX14xm1T5H7phijxoxtKQ',
    appId: '1:825089598653:ios:a469ffa19401048b2e83d4',
    messagingSenderId: '825089598653',
    projectId: 'firestore-1b054',
    storageBucket: 'firestore-1b054.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2HpaUBVqUeCMX14xm1T5H7phijxoxtKQ',
    appId: '1:825089598653:ios:a469ffa19401048b2e83d4',
    messagingSenderId: '825089598653',
    projectId: 'firestore-1b054',
    storageBucket: 'firestore-1b054.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcscO9vECkwxPtLZ9YumQhx1LDbtnc37w',
    appId: '1:825089598653:web:9c2f816b80d2bf3f2e83d4',
    messagingSenderId: '825089598653',
    projectId: 'firestore-1b054',
    authDomain: 'firestore-1b054.firebaseapp.com',
    storageBucket: 'firestore-1b054.appspot.com',
    measurementId: 'G-DM9DWF89MV',
  );
}
